Added Pre commincs and removed sensitive data
I used git-filter-repo to remove sensitive data from the git history. I used the following command to remove the sensitive data from the git history:

I ran the following command:
git filter-repo --path example_data/COPDGeneCounts.csv \
                --path example_data/COPDGeneMetadata.csv \
                --path example_data/metabolites_blood_count_adjusted_2019-08-26.csv \
                --path example_data/proteins_blood_count_adjusted_protein_names.csv \
                --path example_data/Y_finalgold_coarse.csv \
                --invert-paths --force
then I ran to remove it from the history of every branch:
git push --force --all
git push --force --tags

This can cause conflict with your local branch.
I recommend deleting your local branch and pulling the remote branch again.

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -31,6 +31,9 @@ jobs:
           pip install torch_geometric
         shell: bash
 
+      - name: Verify Documentation Directory
+        run: test -d docs/source/ || { echo "Docs source directory missing"; exit 1; }
+
       - name: Build Documentation
         run: |
           mkdir -p docs/build/html
